### ISSUE TITLE
关于 筛选圣遗物 

### ISSUE THREAD

**Issue by AKIRAasf** [zyr17/AmenomaCocogoat#1]
20级的圣遗物 根据圣遗物双爆评分（暴击*2+爆伤*1）大于x分 筛选  不知道可行？？

**Comment by zyr17** [comment]
稍微有点麻烦，基本上就是把莫娜占卜屋的评分系统集成到过滤器中。可以做，但是近期没有时间。春节期间看看有没有空。

**Comment by tseflcz** [comment]
我写了一个评分系统https://github.com/tseflcz/artifacts-master/，个人觉得还挺好用的，不知道有没有可能集成到加锁工具中去。

**Comment by zyr17** [comment]
> 我写了一个评分系统[https://github.com/tseflcz/artifacts-master/，个人觉得还挺好用的，不知道有没有可能集成到加锁工具中去。](https://github.com/tseflcz/artifacts-master/%EF%BC%8C%E4%B8%AA%E4%BA%BA%E8%A7%89%E5%BE%97%E8%BF%98%E6%8C%BA%E5%A5%BD%E7%94%A8%E7%9A%84%EF%BC%8C%E4%B8%8D%E7%9F%A5%E9%81%93%E6%9C%89%E6%B2%A1%E6%9C%89%E5%8F%AF%E8%83%BD%E9%9B%86%E6%88%90%E5%88%B0%E5%8A%A0%E9%94%81%E5%B7%A5%E5%85%B7%E4%B8%AD%E5%8E%BB%E3%80%82)

非常感谢您提供的代码和思路！通过评分设置和同部位套装结合的筛选我一直想做，能有您的代码可以节省不少功夫。只不过这块工作量较大（前端设计，各模块交互逻辑），春节期间似乎也很难有很充分的时间，空下来后我会研究下如何集成比较好。

**Comment by zyr17** [comment]
我已经将圣遗物过滤相关内容集成到[tseflcz](https://github.com/tseflcz)大佬的https://github.com/tseflcz/artifacts-master 中，该网页包含对圣遗物的评分，同时可以结合yas-lock对圣遗物加解锁，推荐使用。
