### ISSUE TITLE
关于新圣遗物

### ISSUE THREAD

**Issue by ForeverNightmare** [zyr17/AmenomaCocogoat#2]
请问新圣遗物无法识别出来是因为单纯的没有做对应的识别处理么？还是做了识别但是BUG了

**Comment by zyr17** [comment]
amenoma的框架不支持直接更新新圣遗物，需要训练新的模型。然后amenoma在我fork的版本之后做了一次大重构，导致模型和我的代码版本不兼容了，就没来得及更新。。我这段时间会尽快重新训练一个模型更新新版本，没更新之前很抱歉暂时无法识别新圣遗物。

**Comment by ForeverNightmare** [comment]
> amenoma的框架不支持直接更新新圣遗物，需要训练新的模型。然后amenoma在我fork的版本之后做了一次大重构，导致模型和我的代码版本不兼容了，就没来得及更新。。我这段时间会尽快重新训练一个模型更新新版本，没更新之前很抱歉暂时无法识别新圣遗物。

没事没事，完全没有必要道歉啊，我这种直接用便利的工具的太过意不去了，整个重构了工程量大加上年底了忙完全能理解的
之前我没读amenoma的代码，以为单纯是用OCR做了文字识别，新圣遗物可以直接识别，就比较疑惑是不是出了bug，没想到还是训练了模型的

**Comment by zyr17** [comment]
已经发布0.3版了，应该可以支持新圣遗物了。
